<?php

/**
 * Docexa Doctor Micro Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: satish.soni@globalspace.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

namespace App\Http\Controllers;

use Illuminate\Http\Response;
use Illuminate\Http\Request;
use App\Doctor;
use DB;
use Log;

class AdminApi extends Controller
{

    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation Admin
     *
     * @return Http response
     */
    /**

     * @OA\Get(
     * path="/admin/doctor",
     * tags={"Admin"},
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.", 
     *     ),
     * )
     */
    public function getdoctors()
    {
        
        //$data = Doctor::paginate(50);

        $data = DB::table('docexa_medical_establishments')
            ->Join('docexa_medical_establishments_medical_user_map', 'docexa_medical_establishments_medical_user_map.medical_establishment_id', '=', 'docexa_medical_establishments.id')
            ->Join('docexa_doctor_master', 'docexa_medical_establishments_medical_user_map.medical_user_id', '=', 'docexa_doctor_master.pharmaclient_id')
            ->select('docexa_doctor_master.activation_flag','docexa_doctor_master.mobile_no', 'docexa_doctor_master.mrn_council_year', 'docexa_doctor_master.mrn_council_state_id', 'docexa_doctor_master.medical_registration_no', 'docexa_doctor_master.speciality_id', 'docexa_doctor_master.image', 'docexa_doctor_master.pharmaclient_name', 'docexa_doctor_master.last_name', 'docexa_doctor_master.address', 'docexa_doctor_master.pharmaclient_image', 'docexa_medical_establishments_medical_user_map.id', 'docexa_medical_establishments_medical_user_map.handle', 'docexa_medical_establishments_medical_user_map.medical_establishment_id', 'docexa_medical_establishments_medical_user_map.medical_user_id', 'docexa_medical_establishments.address_id')
            ->paginate(50);
        return response()->json(['status' => 'success', 'data' => $data], 200);
    }
    /**
     * Operation Admin
     *
     * @return Http response
     */
    /**

     * @OA\Put(
     * path="/admin/doctor/{medical_user_id}/active",
     * tags={"Admin"},
     * @OA\Parameter(
     *         name="medical_user_id",
     *         in="path",
     *         description="medical_user_id",
     *         required=true,
     *         example=24,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.", 
     *     ),
     * )
     */
    /**

     * @OA\Put(
     * path="/admin/doctor/{medical_user_id}/inactive",
     * tags={"Admin"},
     * @OA\Parameter(
     *         name="medical_user_id",
     *         in="path",
     *         description="medical_user_id",
     *         required=true,
     *         example=24,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.", 
     *     ),
     * )
     */
    public function updatedoctoractive($medical_user_id)
    {
        
        //$data = Doctor::paginate(50);

        $doctor = Doctor::find($medical_user_id);
        $doctor->activation_flag = 1;
        $doctor->save();

        return $this->getdoctors();
    }
    public function updatedoctorinactive($medical_user_id)
    {
        
        //$data = Doctor::paginate(50);

        $doctor = Doctor::find($medical_user_id);
        $doctor->activation_flag = 0;
        $doctor->save();

        return $this->getdoctors();
    }
}