<?php

/**
 * Docexa Doctor Micro Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: satish.soni@globalspace.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

namespace App\Http\Controllers;

use Illuminate\Http\Response;
use Illuminate\Http\Request;
use Storage;
use DB;
use Log;
use App\Jobs\updateStatus;
//use App\AppointmentDetails;
use Carbon\Carbon;
class JobApi extends Controller
{

    /**
     * Constructor
     */
    public function __construct()
    {
    }

    public function index()
    {
      
        error_log(Carbon::now());
        $start = Carbon::now();
        error_log($start);
        
        $appt = 'f8eb278a8bce873ef365b45e939da38a';
        $us = new updateStatus($appt);
        $us->apptID();
        dispatch((new updateStatus($appt))->delay($start->addMinutes(2)));
        
    }
}
