<?php

/**
 * Docexa Doctor Micro Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: satish.soni@globalspace.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

namespace App\Http\Controllers;

//use Illuminate\Support\Facades\Request;
use Illuminate\Http\Response;
use Illuminate\Http\Request;
use App\Speciality;
use App\Prescriptiontemplate;
use Storage;
use Config;
use DB;
use Log;

class MasterApi extends Controller
{

    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation getLocation
     *
     * Send OTP.
     *
     * @param number $mobileno send otp  (required)
     *
     * @return Http response
     */

    /**

     * @OA\Get(
     * path="/doctors/location",
     * tags={"Master"},
     *  
     * @OA\Response(
     *         response="200",
     *         description="location data",
     *    @OA\JsonContent(
     *       @OA\Property(property="success", type="string", example="success")
     *        )
     *     )
     *     ),
     * )
     */
    public function getlocation(Request $request)
    {
        $req = $request->all();
        if (isset($req['location']))
            $data = DB::table('docexa_medical_establishments_medical_user_map')
            ->join('docexa_doctor_master','docexa_doctor_master.pharmaclient_id','docexa_medical_establishments_medical_user_map.medical_user_id')
            ->select('docexa_medical_establishments_medical_user_map.id as address_id', 'docexa_medical_establishments_medical_user_map.city')
            ->where('docexa_medical_establishments_medical_user_map.city','like', $req['location'] . '%')
            ->where('docexa_doctor_master.search_flag',1)
            ->groupBy('docexa_medical_establishments_medical_user_map.city')->get();
        else
        $data = DB::table('docexa_medical_establishments_medical_user_map')
        ->join('docexa_doctor_master','docexa_doctor_master.pharmaclient_id','docexa_medical_establishments_medical_user_map.medical_user_id')
        ->select('docexa_medical_establishments_medical_user_map.id as address_id', 'docexa_medical_establishments_medical_user_map.city')
        ->where('docexa_doctor_master.search_flag',1)
        ->groupBy('docexa_medical_establishments_medical_user_map.city')->get();
        return response()->json(['status' => 'success', 'data' => $data], 200);
    }
    /**  @OA\Get(
        * path="/doctors/specilization",
        * tags={"Master"},
        *  
        * @OA\Response(
        *         response="200",
        *         description="specilization data",
        *    @OA\JsonContent(
        *       @OA\Property(property="success", type="string", example="success")
        *        )
        *     )
        *     ),
        * )
        */
    public function getspecilization(Request $request)
    {
        $req = $request->all();
        if (isset($req['specilization']))
            $data = Speciality::select('speciality_id', 'speciality_name')->where('search_flag',1)->where('speciality_name','like', $req['specilization'] . '%')->get();
        else
            $data = Speciality::select('speciality_id', 'speciality_name')->get();
        return response()->json(['status' => 'success', 'data' => $data], 200);
    }
    /**  @OA\Get(
        * path="/prescription/sample",
        * tags={"Master"},
        *  
        * @OA\Response(
        *         response="200",
        *         description="specilization data",
        *    @OA\JsonContent(
        *       @OA\Property(property="success", type="string", example="success")
        *        )
        *     )
        *     ),
        * )
        */
        public function prescription_template()
        {
            $data = Prescriptiontemplate::all();
            return response()->json(['status' => 'success', 'data' => $data], 200);
        }
    /**  @OA\Get(
        * path="/profile/statemedicalcouncil",
        * tags={"Master"},
        *  
        * @OA\Response(
        *         response="200",
        *         description="State Medical Council data",
        *    @OA\JsonContent(
        *       @OA\Property(property="success", type="string", example="success")
        *        )
        *     )
        *     ),
        * )
        */
        public function StateMedicalCouncil()
        {
            $data = DB::table('docexa_medical_council_state_master')->get();
            return response()->json(['status' => 'success', 'data' => $data], 200);
        }
        /**  @OA\Get(
        * path="/profile/state",
        * tags={"Master"},
        *  
        * @OA\Response(
        *         response="200",
        *         description="State data",
        *    @OA\JsonContent(
        *       @OA\Property(property="success", type="string", example="success")
        *        )
        *     )
        *     ),
        * )
        */
        public function state()
        {
            $data = DB::table('docexa_state_master')->select('state_id','state_name','country_id')->get();
            return response()->json(['status' => 'success', 'data' => $data], 200);
        }
        /**  @OA\Get(
        * path="/profile/city/{stateID}",
        * tags={"Master"},
        * @OA\Parameter(
     *         name="stateID",
     *         in="path",
     *         description="stateID",
     *         required=true,
     *         @OA\Items(type="integer")
     *     ),
        * @OA\Response(
        *         response="200",
        *         description="State data",
        *    @OA\JsonContent(
        *       @OA\Property(property="success", type="string", example="success")
        *        )
        *     )
        *     ),
        * )
        */
        public function city($stateID)
        {
            $data = DB::table('city_master')->where('state_id',$stateID)->orderBy('city_master.name')->get();
            return response()->json(['status' => 'success', 'data' => $data], 200);
        }
}
