<?php

/**
 * Docexa Doctor Micro Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: satish.soni@globalspace.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

namespace App\Http\Controllers;

use App\Skumaster;
use Illuminate\Http\Response;
use Illuminate\Http\Request;
use DB;
use Log;

class SkuApi extends Controller
{

    /**
     * Constructor
     */
    public function __construct()
    {
    }
    /**
     * @OA\Get(
     * path="/establishments/users/{esteblishmentUserMapID}/skus",
     * tags={"Establishments"},
     *    
     * @OA\Parameter(
     *         name="esteblishmentUserMapID",
     *         in="path",
     *         description="esteblishmentUserMapID",
     *         required=true,
     *         example=6257,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Response(
     *         response="200",
     *         description="sku detail master data",
     *    @OA\JsonContent(
     *       @OA\Property(property="success", type="string", example="success")
     *        )
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.",    
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="esteblishment User Map ID not found")
     *        )
     *     ),
     * )
     */
    public function skudetails($esteblishmentUserMapID)
    {

        if (!isset($esteblishmentUserMapID)) {
            return response()->json(['status' => 'fail', 'msg' => 'esteblishment User Map ID not found'], 400);
        }
        $res = new Skumaster();
        $data = $res->getskudetails($esteblishmentUserMapID);
        return $data;
    }
    /**
     * @OA\Get(
     * path="/establishments/hospital/{hospitalID}/users/{esteblishmentUserMapID}/skus",
     * tags={"Hospitals"},
     *    
     * @OA\Parameter(
     *         name="esteblishmentUserMapID",
     *         in="path",
     *         description="esteblishmentUserMapID",
     *         required=true,
     *         example=6257,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Parameter(
     *         name="hospitalID",
     *         in="path",
     *         description="hospitalID",
     *         required=true,
     *         example=1,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Response(
     *         response="200",
     *         description="sku detail master data",
     *    @OA\JsonContent(
     *       @OA\Property(property="success", type="string", example="success")
     *        )
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.",    
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="esteblishment User Map ID not found")
     *        )
     *     ),
     * )
     */
    public function hospitalskudetails($esteblishmentUserMapID,$hospitalID)
    {

        if (!isset($esteblishmentUserMapID)) {
            return response()->json(['status' => 'fail', 'msg' => 'esteblishment User Map ID not found'], 400);
        }
        $res = new Skumaster();
        $data = $res->gethospitalskudetails($esteblishmentUserMapID,$hospitalID);
        return $data;
    } 
    /**

     * @OA\Put(
     * path="/establishments/users/{esteblishmentUserMapID}/skus",
     * tags={"Establishments"},
     *    
     * @OA\Parameter(
     *         name="esteblishmentUserMapID",
     *         in="path",
     *         description="esteblishmentUserMapID",
     *         required=true,
     *         example=6257,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\RequestBody(
     *  required=true,
     *  description="Mode = 1 //online, Mode = 2  //In Clinic, Mode = 3 //both",
     *  @OA\JsonContent(
     *      type="object",
     *      @OA\Property(property="title", type="string", example="Regular Consultation"),
     *      @OA\Property(property="description", type="string", example="Any questions around vaccines and well being"),
     *      @OA\Property(property="price", type="number", example="100"),
     *      @OA\Property(property="mode", type="number", example="1"),
     *      @OA\Property(property="clinic_id", type="number", example="100")
     *  ),
     * ),
     * @OA\Response(
     *         response="200",
     *         description="sku detail master data",
     *    @OA\JsonContent(
     *       @OA\Property(property="success", type="string", example="success")
     *        )
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.",    
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="esteblishment User Map ID not found")
     *        )
     *     ),
     * )
     */
    public function addsku($esteblishmentUserMapID,Request $request)
    {

        if (!isset($esteblishmentUserMapID)) {
            return response()->json(['status' => 'fail', 'msg' => 'esteblishment User Map ID not found'], 400);
        }
        $res = new Skumaster();
        $data = $res->setskudetails($esteblishmentUserMapID,$request);
        return $data;
    }
    /**

     * @OA\Patch(
     * path="/establishments/users/{esteblishmentUserMapID}/skus/{id}",
     * tags={"Establishments"},
     *    
     * @OA\Parameter(
     *         name="esteblishmentUserMapID",
     *         in="path",
     *         description="esteblishmentUserMapID",
     *         required=true,
     *         example=6257,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Parameter(
     *         name="id",
     *         in="path",
     *         description="id",
     *         required=true,
     *         example=197443,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\RequestBody(
     *  required=true,
     *  description="Mode = 1 //online, Mode = 2  //In Clinic, Mode = 3 //both",
     *  @OA\JsonContent(
     *      type="object",
     *      @OA\Property(property="title", type="string", example="Regular Consultation"),
     *      @OA\Property(property="description", type="string", example="Any questions around vaccines and well being"),
     *      @OA\Property(property="price", type="number", example="100"),
     *      @OA\Property(property="mode", type="number", example="1")
     *  ),
     * ),
     * @OA\Response(
     *         response="200",
     *         description="sku detail master data",
     *    @OA\JsonContent(
     *       @OA\Property(property="success", type="string", example="success")
     *        )
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.",    
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="esteblishment User Map ID not found")
     *        )
     *     ),
     * )
     */
    public function editsku($esteblishmentUserMapID,$id,Request $request)
    {

        if (!isset($esteblishmentUserMapID)) {
            return response()->json(['status' => 'fail', 'msg' => 'esteblishment User Map ID not found'], 400);
        }
        $res = new Skumaster();
        $data = $res->editskudetails($esteblishmentUserMapID,$id,$request);
        return $data;
    }
    /**

     * @OA\Delete(
     * path="/establishments/users/{esteblishmentUserMapID}/skus/{id}",
     * tags={"Establishments"},
     *    
     * @OA\Parameter(
     *         name="esteblishmentUserMapID",
     *         in="path",
     *         description="esteblishmentUserMapID",
     *         required=true,
     *         example=6257,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Parameter(
     *         name="id",
     *         in="path",
     *         description="id",
     *         required=true,
     *         example=1,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Response(
     *         response="200",
     *         description="sku detail master data",
     *    @OA\JsonContent(
     *       @OA\Property(property="success", type="string", example="success")
     *        )
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.",    
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="esteblishment User Map ID not found")
     *        )
     *     ),
     * )
     */
    public function deletesku($esteblishmentUserMapID,$id)
    {

        if (!isset($esteblishmentUserMapID)) {
            return response()->json(['status' => 'fail', 'msg' => 'esteblishment User Map ID not found'], 400);
        }
        $res = new Skumaster();
        $data = $res->deleteskudetails($esteblishmentUserMapID,$id);
        return $data;
    }  
    /**

     * @OA\Patch(
     * path="/establishments/users/{esteblishmentUserMapID}/skus/{id}/default",
     * tags={"Establishments"},
     *    
     * @OA\Parameter(
     *         name="esteblishmentUserMapID",
     *         in="path",
     *         description="esteblishmentUserMapID",
     *         required=true,
     *         example=6257,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Parameter(
     *         name="id",
     *         in="path",
     *         description="id",
     *         required=true,
     *         example=1,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Response(
     *         response="200",
     *         description="sku detail master data",
     *    @OA\JsonContent(
     *       @OA\Property(property="success", type="string", example="success")
     *        )
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.",    
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="esteblishment User Map ID not found")
     *        )
     *     ),
     * )
     */
    public function setdefaultskudetails($esteblishmentUserMapID,$id)
    {

        if (!isset($esteblishmentUserMapID)) {
            return response()->json(['status' => 'fail', 'msg' => 'esteblishment User Map ID not found'], 400);
        }
        $res = new Skumaster();
        $data = $res->setdefaultskudetails($esteblishmentUserMapID,$id);
        return $data;
    }
    /**

     * @OA\Patch(
     * path="/establishments/users/{esteblishmentUserMapID}/skus/{id}/disable",
     * tags={"Establishments"},
     *    
     * @OA\Parameter(
     *         name="esteblishmentUserMapID",
     *         in="path",
     *         description="esteblishmentUserMapID",
     *         required=true,
     *         example=6257,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Parameter(
     *         name="id",
     *         in="path",
     *         description="id",
     *         required=true,
     *         example=1,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Response(
     *         response="200",
     *         description="sku detail master data",
     *    @OA\JsonContent(
     *       @OA\Property(property="success", type="string", example="success")
     *        )
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.",    
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="esteblishment User Map ID not found")
     *        )
     *     ),
     * )
     */
    public function updatestatusdisable($esteblishmentUserMapID,$id)
    {

        if (!isset($esteblishmentUserMapID)) {
            return response()->json(['status' => 'fail', 'msg' => 'esteblishment User Map ID not found'], 400);
        }
        $res = new Skumaster();
        $data = $res->updatestatusdisable($esteblishmentUserMapID,$id);
        return $data;
    }  
    /**

     * @OA\Patch(
     * path="/establishments/users/{esteblishmentUserMapID}/skus/{id}/enable",
     * tags={"Establishments"},
     *    
     * @OA\Parameter(
     *         name="esteblishmentUserMapID",
     *         in="path",
     *         description="esteblishmentUserMapID",
     *         required=true,
     *         example=6257,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Parameter(
     *         name="id",
     *         in="path",
     *         description="id",
     *         required=true,
     *         example=1,
     *         @OA\Schema(type="number")
     *     ),
     * @OA\Response(
     *         response="200",
     *         description="sku detail master data",
     *    @OA\JsonContent(
     *       @OA\Property(property="success", type="string", example="success")
     *        )
     *     ),
     * @OA\Response(
     *         response="400",
     *         description="Error: Bad request. required parameters is not supplied.",    
     *    @OA\JsonContent(
     *       @OA\Property(property="error", type="string", example="esteblishment User Map ID not found")
     *        )
     *     ),
     * )
     */
    public function updatestatusenable($esteblishmentUserMapID,$id)
    {

        if (!isset($esteblishmentUserMapID)) {
            return response()->json(['status' => 'fail', 'msg' => 'esteblishment User Map ID not found'], 400);
        }
        $res = new Skumaster();
        $data = $res->updatestatusenable($esteblishmentUserMapID,$id);
        return $data;
    }    
    
}
